/**
 * Shared "generate an invoice from a recurring template" logic.
 *
 * Used by both the daily cron at /api/cron/recurring-invoices (loops over
 * every active template whose next_run_date has arrived) and the manual
 * "Generate now" button on the template detail page (fires for a single
 * template, on demand, ignoring the next_run_date check).
 *
 * Centralized so the two callers can't drift apart on number generation,
 * tax math, or template-advancement behaviour.
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import type { Invoice } from './invoices';
import { nextInvoiceNumber, round2 } from './invoices';
import { sendInvoiceEmail } from './invoice-send';
import { FALLBACK_TEMPLATE, substituteTemplate } from './invoice-email';
import {
  advanceNextRun, computeDueDate,
  type RecurringTemplate, type RecurringLineItem,
} from './recurring-invoices';

export interface GenerateOptions {
  /** When true, use today's date as the issue date instead of the
   *  template's next_run_date. Used by the manual "Generate now" button
   *  — the operator wants today's date on the invoice, not whatever was
   *  on the schedule. */
  useToday?: boolean;
  /** When true, skip advancing the template's next_run_date. Manual
   *  generation typically wants to advance (so the operator doesn't
   *  accidentally generate two invoices for the same cycle); cron always
   *  advances. */
  skipAdvance?: boolean;
}

export interface GenerateResult {
  invoice: Invoice;
  invoice_number: string;
  sent: boolean;
  send_error?: string;
}

/**
 * Generate an invoice from a recurring template + send the email if the
 * template's `on_generate='send_immediately'`. Caller passes the supabase
 * client (session-scoped or service-role; either works) and the template.
 * Line items are looked up fresh — no need for the caller to pre-fetch.
 *
 * Throws on hard failures (DB errors). Email-send failures are caught and
 * returned as `send_error` on the result so the caller can surface them
 * to the operator without losing the invoice.
 */
export async function generateInvoiceFromTemplate(
  supabase: SupabaseClient,
  tpl: RecurringTemplate,
  options: GenerateOptions = {},
): Promise<GenerateResult> {
  // 1. Pull line items
  const { data: itemsData } = await supabase
    .from('recurring_invoice_line_items')
    .select('*')
    .eq('template_id', tpl.id)
    .order('sort_order');
  const lineItems = (itemsData as RecurringLineItem[] | null) ?? [];

  if (lineItems.length === 0) {
    throw new Error('Template has no line items — add at least one before generating');
  }

  // 2. Determine issue + due dates
  const issueDate = options.useToday
    ? new Date().toISOString().slice(0, 10)
    : tpl.next_run_date;
  const dueDate = computeDueDate(issueDate, tpl.due_days);

  // 3. Generate the invoice number — counts existing invoices in the
  //    issue year. Not race-safe under concurrent generation; in
  //    practice the cron runs once daily and manual is a button-click.
  const year = new Date(issueDate).getUTCFullYear();
  const { count } = await supabase
    .from('invoices')
    .select('id', { count: 'exact', head: true })
    .gte('issue_date', `${year}-01-01`)
    .lte('issue_date', `${year}-12-31`);
  const invoiceNumber = nextInvoiceNumber(count ?? 0, year);

  // 4. Compute totals
  let subtotal = 0;
  for (const li of lineItems) subtotal += Number(li.amount);
  subtotal = round2(subtotal);
  const taxAmount = round2(subtotal * Number(tpl.tax_rate));
  const total = round2(subtotal + taxAmount);

  const initialStatus = tpl.on_generate === 'send_immediately' ? 'sent' : 'draft';

  // 5. Insert the invoice row
  const { data: created, error: invErr } = await supabase
    .from('invoices')
    .insert([{
      invoice_number: invoiceNumber,
      client_name: tpl.client_name,
      client_email: tpl.client_email,
      client_company: tpl.client_company,
      client_address: tpl.client_address,
      issue_date: issueDate,
      due_date: dueDate,
      status: initialStatus,
      subtotal,
      tax_rate: tpl.tax_rate,
      tax_amount: taxAmount,
      total,
      property_reference: tpl.property_reference,
      notes: tpl.notes,
      internal_notes: `Generated by recurring template "${tpl.name}" (${tpl.id})\n${tpl.internal_notes ?? ''}`.trim(),
      payment_terms: tpl.payment_terms,
      recurring_template_id: tpl.id,
      sent_at: initialStatus === 'sent' ? new Date().toISOString() : null,
      reminders_enabled: true,
    }])
    .select('*')
    .single();

  if (invErr) throw new Error(invErr.message);
  const invoice = created as Invoice;

  // 6. Clone line items into invoice_line_items
  const { error: liErr } = await supabase
    .from('invoice_line_items')
    .insert(lineItems.map((li, idx) => ({
      invoice_id: invoice.id,
      description: li.description,
      quantity: li.quantity,
      rate: li.rate,
      amount: li.amount,
      sort_order: li.sort_order ?? idx,
    })));
  if (liErr) {
    // Best-effort rollback so we never leave a header without lines.
    await supabase.from('invoices').delete().eq('id', invoice.id);
    throw new Error(`Line item clone failed: ${liErr.message}`);
  }

  // 7. Advance the template (unless caller explicitly opted out)
  if (!options.skipAdvance) {
    const nextRun = advanceNextRun(
      // Always advance from the template's own next_run_date, even when
      // issuing today — otherwise rapid-fire manual generation would
      // skip cycles.
      tpl.next_run_date,
      tpl.frequency,
    );
    await supabase
      .from('recurring_invoice_templates')
      .update({
        next_run_date: nextRun,
        last_run_at: new Date().toISOString(),
        last_run_invoice_id: invoice.id,
      })
      .eq('id', tpl.id);
  }

  // 8. Fire the email if the template is configured for auto-send. Catch
  //    failures so the invoice still ends up created — the operator can
  //    re-send manually from the detail page.
  let sent = false;
  let send_error: string | undefined;
  if (tpl.on_generate === 'send_immediately') {
    try {
      const { data: settings } = await supabase
        .from('invoice_settings')
        .select('default_subject, default_message')
        .eq('id', 1)
        .single();
      const template = settings ?? FALLBACK_TEMPLATE;
      const fullInvoice = {
        ...invoice,
        line_items: lineItems.map((li, idx) => ({ ...li, sort_order: li.sort_order ?? idx })),
      };
      await sendInvoiceEmail({
        invoice: fullInvoice,
        subject: substituteTemplate(template.default_subject, fullInvoice),
        message: substituteTemplate(template.default_message, fullInvoice),
      });
      sent = true;
    } catch (err) {
      send_error = err instanceof Error ? err.message : String(err);
      console.error('[recurring-generate] email send failed:', send_error);
    }
  }

  return { invoice, invoice_number: invoiceNumber, sent, send_error };
}
