-- ============================================================================
-- San Antonio & Hill Country refocus + "Elkhorn Pointe" rename — CMS data sync
--
-- The four /texas-*-for-lease|for-sale pages merge the landing_pages CMS row
-- OVER their code config (PropertyLandingPage mergeConfig + generateMetadata):
-- a populated row wins for meta title/description, eyebrow, H1, subhead,
-- market bullets, why bullets and FAQs. Those rows still carry the old
-- statewide copy (Austin/Houston/DFW, El Paso, unsourced statewide rates), so
-- the code refocus does not show on the live pages until this runs.
--
-- Section 1 is GENERATED from the page configs in src/app/texas-*/page.tsx —
-- it makes each row match the code exactly (admin Landing Pages editor keeps
-- working; it just starts from the new copy). Section 2 renames the brand in
-- the remaining DB copy. Slugs/URLs are untouched.
--
-- Not applied automatically. Run once in the Supabase SQL editor (website
-- project) AFTER the code deploys. Idempotent: safe to re-run.
-- ============================================================================

begin;

-- ---- 1. Statewide landing pages → San Antonio & the Hill Country ----------

-- /texas-retail-space-for-lease
update public.landing_pages set
  meta_title       = $lp$Retail Space for Lease in San Antonio & the Hill Country | CRECO$lp$,
  meta_description = $lp$Retail space for lease in San Antonio and the Texas Hill Country — strip centers, restaurant space, inline shop space and pads in Stone Oak, Leon Springs, Fair Oaks Ranch, Boerne and the I-10 corridor.$lp$,
  eyebrow          = $lp$San Antonio & Hill Country · Retail$lp$,
  h1               = $lp$Retail Space for Lease in San Antonio & the Texas Hill Country$lp$,
  subhead          = $lp$Strip centers, restaurant space, inline shop space, pads, and mixed-use storefronts — in San Antonio and the Hill Country, from Stone Oak and the I-10 corridor to Leon Springs, Fair Oaks Ranch, and Boerne. Whether you're a single-location operator scouting your first space or a franchise developer planning several locations, CRECO brings options that match your concept, traffic counts, demographics, and budget — from a team that owns and leases retail here itself.$lp$,
  market_bullets   = $lp$[{"title":"Growth is moving north and west.","body":"New rooftops along Loop 1604, the I-10 corridor toward Boerne, and the Hill Country communities are pulling neighborhood retail, restaurant, medical, and service tenants outward. Well-located new space in those corridors is limited, so the best positions are worth locking in early."},{"title":"Submarket fundamentals matter more than ever.","body":"The right retail location is determined by traffic counts, demographics, co-tenancy, and signage visibility — not just price per SF. CRECO underwrites every site against your specific concept and target customer."},{"title":"Lease structures are negotiable.","body":"Tenant improvement allowances, free rent, percentage rent, exclusivity clauses, and CAM caps all move with the right negotiator. We close the gap between asking rent and effective rent."}]$lp$::jsonb,
  why_bullets      = $lp$["Tenant representation for retail and restaurant concepts — from a team that owns and leases its own retail centers in Fair Oaks Ranch and Lytle","Local knowledge of San Antonio and Hill Country corridors — Stone Oak, Leon Springs and I-10, Fair Oaks Ranch, and Boerne","Traffic-count, demographic, and co-tenancy analysis on every shortlist site","LOI and lease negotiation focused on tenant improvement allowances, free rent, and exclusivity","Buildout coordination from architect to grand opening"]$lp$::jsonb,
  faqs             = $lp$[{"q":"How much does retail space cost in San Antonio and the Hill Country?","a":"It depends heavily on the corridor, the center, and the position within it — an end-cap with drive-thru potential on a signalized corner prices very differently from inline space set back from the road, and new construction prices differently from second-generation space. Most retail here is quoted triple-net (NNN), so compare base rent plus the NNN estimate, and weigh tenant improvement allowance and free rent alongside the rate. Our San Antonio retail space page has CRECO's current estimates by retail type; for comps on a specific site, call (210) 817-3443."},{"q":"How long is a typical retail lease?","a":"Initial retail leases are typically 5 to 10 years, often with renewal options. Restaurants and franchisees typically commit to longer terms (7-10 years) in exchange for buildout allowances; pop-up and short-term tenants can sometimes negotiate 1-3 year terms in softer centers."},{"q":"What is \"NNN\" and how does it affect my retail rent?","a":"Triple-net (NNN) means the tenant pays a base rent plus their proportional share of the property's taxes, insurance, and common area maintenance (CAM). Always ask the landlord for the actual NNN figure (not just an estimate) and request CAM reconciliations from prior years before signing."},{"q":"Can CRECO help with restaurant space specifically?","a":"Yes. Restaurant deals require special diligence — grease trap, hood ventilation, parking ratios, alcohol licensing and zoning, drive-thru permitting, and patio rights all matter. We know what to look for on a site and what to negotiate in the lease."},{"q":"I have an existing retail lease — can you help me renew or relocate?","a":"Absolutely. Renewal-vs-relocation analysis is one of the highest-leverage CRECO services. We benchmark your current rent against the market, identify alternative options, and use that competitive tension to negotiate a stronger renewal — or move you somewhere better."},{"q":"Do you only work in San Antonio and the Hill Country?","a":"That is where we focus and where we own property. If you're a tenant with a requirement elsewhere in Texas, we can help there too."}]$lp$::jsonb,
  updated_at       = now()
where slug = 'texas-retail-space-for-lease';

-- /texas-office-space-for-lease
update public.landing_pages set
  meta_title       = $lp$Office Space for Lease in San Antonio & the Hill Country | CRECO$lp$,
  meta_description = $lp$Office space for lease in San Antonio and the Texas Hill Country — Class A and B, medical office, professional and executive suites in Stone Oak, the Medical Center, the I-10 corridor, Fair Oaks Ranch and Boerne.$lp$,
  eyebrow          = $lp$San Antonio & Hill Country · Office$lp$,
  h1               = $lp$Office Space for Lease in San Antonio & the Texas Hill Country$lp$,
  subhead          = $lp$Class A and B office, medical office, professional suites, and executive office — in San Antonio and the Hill Country, from Stone Oak, the Medical Center, and the I-10 corridor to Fair Oaks Ranch and Boerne. Whether you need a single executive suite or a full floor, CRECO matches your team size, growth path, and commute to the right building — and we lease executive suites in our own Fair Oaks Plaza.$lp$,
  market_bullets   = $lp$[{"title":"Office is bifurcating.","body":"Newer, well-amenitized space is in tight supply and commands premium rents, while older Class B space is easier to find — meaning generous concessions for the right tenant. Knowing which side of the market you want to play on is half the battle."},{"title":"Submarkets vary widely.","body":"Stone Oak is not Downtown. The Medical Center is not the Pearl, and a Hill Country suite in Boerne or Fair Oaks Ranch serves a different team than either. Each submarket has different rent benchmarks, parking ratios, commute patterns, and amenities. We help you pick the right one."},{"title":"Tenant improvement is everything.","body":"Landlords routinely offer tenant improvement allowance and free rent for the right tenant, credit, and term — often enough to fund a meaningful buildout. The asking rent only tells half the story; the effective rent after concessions is the real number."}]$lp$::jsonb,
  why_bullets      = $lp$["Tenant representation across San Antonio and Hill Country office submarkets — Stone Oak, the Medical Center, Northwest San Antonio, the I-10 corridor, Fair Oaks Ranch, and Boerne","Class A/B, medical office, and executive suite expertise — from a team that leases executive suites in its own building","Effective rent analysis — comparing offers net of TI allowance, free rent, and amenities","Buildout coordination from space planning to move-in","Renew vs. relocate analysis to maximize leverage at lease expiration"]$lp$::jsonb,
  faqs             = $lp$[{"q":"What does office space cost in San Antonio and the Hill Country?","a":"It depends on building class, submarket, and how the lease is quoted. Most multi-tenant office is quoted Full Service Gross (rent includes operating expenses), while medical office and some smaller buildings are quoted NNN or modified gross — so normalize offers before comparing them. Our San Antonio office space page has CRECO's current estimates by class; for comps on a specific building, call (210) 817-3443. Always compare effective rent — net of free-rent months and tenant improvement allowance — not just the asking rate."},{"q":"What's the difference between Class A, B, and C office?","a":"Class A: newer construction (typically post-2000), high-end finishes, modern amenities (fitness, conferencing, on-site food, structured parking), prime submarkets, top rents. Class B: well-maintained older buildings (typically 1990s-2000s), functional space, reasonable amenities, good submarkets, mid-market rents. Class C: older buildings (pre-1990s), basic finishes, limited amenities, secondary submarkets, lowest rents. Class B is often the sweet spot for value."},{"q":"How much parking should I expect with office space?","a":"Parking ratios are quoted per 1,000 SF leased. Suburban office typically offers around 4:1000 (4 spaces per 1,000 SF), which works for most companies. Downtown buildings often have less, with paid structured parking. Medical office and call centers may need more. Always confirm in writing — parking ratio is one of the most-disputed lease items."},{"q":"Can I sublease office space?","a":"Yes — sublease can be a good way to save against direct lease rates, especially for terms under 3 years. Subleases come from companies that over-leased and need to offload space. CRECO watches sublease availability in San Antonio and the Hill Country and can shortlist sublease options alongside direct leases."},{"q":"What is \"Full Service Gross\" vs \"NNN\" for office leases?","a":"Full Service Gross (FSG) means the landlord covers operating expenses (taxes, insurance, utilities, janitorial, CAM) within the quoted rent — though tenants pay increases above a base year. NNN means the tenant pays a base rent plus their share of expenses. FSG is the most common structure for multi-tenant office; medical office and some smaller buildings run NNN or modified gross."},{"q":"Do you only work in San Antonio and the Hill Country?","a":"That is where we focus and where we own property. If you're a tenant with a requirement elsewhere in Texas, we can help there too."}]$lp$::jsonb,
  updated_at       = now()
where slug = 'texas-office-space-for-lease';

-- /texas-industrial-property-for-lease
update public.landing_pages set
  meta_title       = $lp$Industrial & Warehouse for Lease in San Antonio & the Hill Country | CRECO$lp$,
  meta_description = $lp$Industrial, warehouse and flex space for lease in San Antonio and the Texas Hill Country — distribution, light manufacturing, flex and service-industrial on the I-35, I-10 and Loop 1604 corridors.$lp$,
  eyebrow          = $lp$San Antonio & Hill Country · Industrial & Warehouse$lp$,
  h1               = $lp$Industrial & Warehouse Space for Lease in San Antonio & the Hill Country$lp$,
  subhead          = $lp$Distribution, light manufacturing, flex-industrial, service-industrial, and contractor space — across San Antonio's industrial submarkets and the I-10 and I-35 corridors into the Hill Country. Whether you need a small flex bay for a service business or a larger distribution building, CRECO brings options with the right clear height, dock-door count, power, parking, and yard.$lp$,
  market_bullets   = $lp$[{"title":"San Antonio sits on the I-35 and I-10 corridors.","body":"The Northeast / I-35 corridor toward Schertz and New Braunfels anchors modern bulk distribution, while infill flex and service-industrial on the North Side and along I-10 toward Boerne serve operators who need to be close to their customers."},{"title":"Specs matter more than rent.","body":"Two warehouses at the same $/SF rate can be wildly different deals. Clear height, dock-door ratios, trailer parking, power capacity (480V vs 277/480V three-phase), sprinkler systems (ESFR vs standard), and yard area all drive your operating cost. CRECO benchmarks every site on these specs."},{"title":"Concessions are still on the table.","body":"Even in tight markets, the right tenant — credit, term length, expansion path — can negotiate free rent, tenant improvement allowances for racking and office buildout, and rent escalators that beat market."}]$lp$::jsonb,
  why_bullets      = $lp$["Detailed property-spec underwriting (clear height, doors, power, sprinkler class, parking)","Submarket comp analysis for honest rent benchmarking","Free-rent and TI-allowance negotiation for racking, office, and buildout","Multi-site strategy for distribution and last-mile expansion","Local coverage: Northeast / I-35, Far Northwest / Loop 1604 and I-10, plus Hill Country flex and service-industrial"]$lp$::jsonb,
  faqs             = $lp$[{"q":"What does industrial space cost in San Antonio?","a":"It depends on submarket, building age, clear height, and bay size — modern bulk distribution, older second-generation warehouse, and small-bay flex with office buildout all price differently. Most industrial is quoted triple-net (NNN). Our San Antonio industrial space page has CRECO's current estimates by product type; for comps on a specific building, call (210) 817-3443."},{"q":"What clear height should I look for?","a":"For typical distribution, 24-32 ft clear height is standard. 18-24 ft is common in older or Class C industrial. Modern bulk distribution centers built since 2018 are often 32-40 ft clear, accommodating 5-6 levels of pallet racking. The right clear height depends on your storage profile — if you stack 4 levels of pallet racking, 24 ft is the minimum; for narrow-aisle automation, 36+ ft is preferred."},{"q":"How many dock doors do I need?","a":"A common rule of thumb is 1 dock door per 5,000-10,000 SF, but it depends on throughput. High-velocity distribution and cross-dock operations may need 1 door per 2,000-3,000 SF. Service or storage operations may only need 1 door per 15,000-20,000 SF. Always confirm whether dock doors are dock-high (typical) or grade-level (drive-in) — they serve different purposes."},{"q":"Where are the main San Antonio-area industrial submarkets?","a":"In San Antonio: the Northeast (the I-35 corridor toward Schertz and New Braunfels) for modern bulk distribution, and the Far Northwest (Loop 1604 / I-10) for flex and smaller-bay product closer to the North Side. Up the I-10 corridor, Boerne and the Hill Country communities have a smaller supply of mostly small-bay flex and service-industrial space. The right one depends on where your customers, employees, and trucks need to go."},{"q":"Can CRECO help with cold storage or specialized industrial?","a":"Yes. Cold storage, food-grade, hazmat-rated, lab, manufacturing with heavy power requirements, and refrigerated distribution all require specialized site selection — and plenty of buildings claim specs they don't actually meet. We verify the specs that matter before you tour."},{"q":"Do you only work in San Antonio and the Hill Country?","a":"That is where we focus and where we own property. If you're a tenant with a requirement elsewhere in Texas, we can help there too."}]$lp$::jsonb,
  updated_at       = now()
where slug = 'texas-industrial-property-for-lease';

-- /texas-commercial-property-for-sale
update public.landing_pages set
  meta_title       = $lp$Commercial Property for Sale in San Antonio & the Hill Country | CRECO$lp$,
  meta_description = $lp$Commercial property for sale in San Antonio and the Texas Hill Country — retail centers, office and industrial buildings, pads and land. Investor, owner-user and 1031 advisory from CRECO.$lp$,
  eyebrow          = $lp$San Antonio & Hill Country · For Sale$lp$,
  h1               = $lp$Commercial Property for Sale in San Antonio & the Texas Hill Country$lp$,
  subhead          = $lp$Retail centers, office and industrial buildings, mixed-use, pads, and commercial land — investment and owner-user opportunities in San Antonio and the Hill Country. Whether you're acquiring your first asset, executing a 1031 exchange, or selling a property you've held for years, CRECO underwrites every deal the way an owner would — because we own and operate commercial property here ourselves.$lp$,
  market_bullets   = $lp$[{"title":"Pricing has reset.","body":"Cap rates have moved out from their 2022 lows, creating entry points for patient capital in the right San Antonio and Hill Country submarkets — and making underwriting discipline matter more than ever."},{"title":"Off-market matters.","body":"Many of the best local deals never hit LoopNet or CoStar. Long-time owners in San Antonio and the Hill Country often sell through relationships, and CRECO's local owner network surfaces opportunities before they reach the open market."},{"title":"1031 timing matters.","body":"Smart commercial investors structure acquisitions around 1031 exchange timing. We coordinate with your CPA and qualified intermediary on tax-driven decisions like 1031 timing, so deals close inside the windows."}]$lp$::jsonb,
  why_bullets      = $lp$["Underwriting and pro forma modeling on every deal we bring to you","Off-market deal flow through our San Antonio and Hill Country owner and broker network","1031 exchange identification with up- and down-leg coordination","Owner-user and investor representation across San Antonio and the Hill Country","An owner-operator's view — CRECO owns and operates Fair Oaks Plaza and our Lytle center"]$lp$::jsonb,
  faqs             = $lp$[{"q":"What cap rates can I expect for commercial property in San Antonio and the Hill Country?","a":"Cap rates vary by asset type, submarket, tenant credit, and remaining lease term — a long-term net lease to a national tenant trades very differently from a multi-tenant center with near-term rollover. Our San Antonio office and industrial pages carry CRECO's current estimates for those asset types; for comps on a specific property, call (210) 817-3443."},{"q":"What's the typical due diligence period in Texas?","a":"Texas commercial transactions typically allow 30-60 days for inspection / due diligence after contract execution, followed by another 30-45 days to close. Diligence covers physical condition, environmental (Phase I and sometimes Phase II), title, survey, lease audit, financial verification, and zoning/entitlement confirmation. We coordinate the full diligence team — attorney, lender, environmental, surveyor, inspector."},{"q":"Can CRECO help with 1031 exchanges?","a":"Absolutely. 1031 exchanges have strict timing rules: 45 days from closing the relinquished property to identify replacement property, 180 days to close. We work in lockstep with your qualified intermediary to identify suitable replacement properties in San Antonio and the Hill Country within the 45-day window — including off-market opportunities that match your basis and DSCR requirements."},{"q":"How do I evaluate a multi-tenant retail or office acquisition?","a":"Beyond cap rate and price-per-SF: tenant credit and lease term remaining (weighted average lease term or WALT), rent rollover risk concentration, operating expense recovery (NNN vs gross leases), capital reserve requirements, market rent vs in-place rent (mark-to-market upside), and submarket vacancy trends. CRECO underwrites every shortlist deal on these factors before you spend due-diligence budget."},{"q":"What about owner-user deals — buying a building for my own business?","a":"Owner-user CRE acquisitions are often more affordable than leasing equivalent space when you factor SBA 504 financing (low down payment, long amortization), tax-deductible depreciation, and equity build-up. We help owner-users compare buy vs lease economics, secure SBA-eligible properties, and structure leases to outside tenants if you have excess space."}]$lp$::jsonb,
  updated_at       = now()
where slug = 'texas-commercial-property-for-sale';

-- ---- 2. "Elkhorn Point" → "Elkhorn Pointe" in DB copy ---------------------
-- (?!e) guard so an already-renamed "Elkhorn Pointe" never becomes "Pointee".
-- The listing slug 'elkhorn-point-back-lot' is deliberately NOT changed.

update public.landing_pages
   set faqs = regexp_replace(faqs::text, 'Elkhorn Point(?!e)', 'Elkhorn Pointe', 'g')::jsonb,
       updated_at = now()
 where slug = '8923-dietz-elkhorn'
   and faqs::text ~ 'Elkhorn Point(?!e)';

update public.listings
   set title       = regexp_replace(title,       'Elkhorn Point(?!e)', 'Elkhorn Pointe', 'g'),
       headline    = regexp_replace(headline,    'Elkhorn Point(?!e)', 'Elkhorn Pointe', 'g'),
       description = regexp_replace(description, 'Elkhorn Point(?!e)', 'Elkhorn Pointe', 'g'),
       features    = array(select regexp_replace(t.f, 'Elkhorn Point(?!e)', 'Elkhorn Pointe', 'g') from unnest(features) with ordinality as t(f, i) order by t.i)
 where slug = 'elkhorn-point-back-lot';

commit;
